# -*- coding: utf-8 -*-
"""Isro_Q&N

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5d_9tJRmrkAeWxvHlWrSoOieSDSGA8-
"""

!pip install -qU langchain langchain-community langchain-huggingface pypdf faiss-cpu

!pip install -qU langchain-huggingface langchain-community faiss-cpu

!pip install langchain faiss-cpu sentence-transformers

!pip install -qU pypdf langchain-community

!pip install -U langchain langchain-community

from langchain_community.document_loaders import TextLoader

from langchain_text_splitters import CharacterTextSplitter

splitter = CharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

docs = splitter.split_documents(documents)

from transformers import pipeline

llm = pipeline("text-generation", model="distilgpt2")



from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

# Create a destination folder
extract_to = "/content/unzipped_isro_data/"
os.makedirs(extract_to, exist_ok=True)

# Path to your folder in Drive
drive_path = "/content/drive/MyDrive/ISRO_Chandrayan3"

# Loop through and unzip all files in that folder
for file in os.listdir(drive_path):
    if file.endswith(".zip"):
        print(f"Unzipping {file}...")
        with zipfile.ZipFile(os.path.join(drive_path, file), 'r') as zip_ref:
            zip_ref.extractall(extract_to)

print("✅ All PDFs extracted to /content/unzipped_isro_data/")

from langchain_community.document_loaders import PyPDFDirectoryLoader

# Use the LOCAL folder where we just unzipped everything
loader = PyPDFDirectoryLoader("/content/unzipped_isro_data/")
documents = loader.load()

# Re-run the splitter
from langchain_text_splitters import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(chunk_size=700, chunk_overlap=100)
chunks = text_splitter.split_documents(documents)

print(f"✅ FINAL SUCCESS: Loaded {len(documents)} pages and split into {len(chunks)} chunks.")

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# 1. Initialize the Embedding Model (The 'Translator')
print("Converting 858 chunks into vectors... this will take a minute.")
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# 2. Create the FAISS Database
vector_store = FAISS.from_documents(chunks, embeddings)
retriever = vector_store.as_retriever(search_kwargs={"k": 3})

print("✅ SUCCESS: Your Chandrayaan-3 Search Engine is ready!")

# Link your 858 chunks to the AI chain
retriever = vector_store.as_retriever(search_kwargs={"k": 5}) # Pull 5 chunks instead of 2

# If you get a NameError here, re-run the cell where you defined 'rag_chain'
print("✅ Retriever is now linked to your 273-page database.")

def ask_isro_ai(user_query):
    docs = retriever.invoke(user_query)
    context_text = "\n\n".join([doc.page_content for doc in docs])

    # Very clear instructions for the AI
    input_text = f"""Instruction: Answer the question based ONLY on the context below.
If the answer is not there, say you don't know.

Context: {context_text}

Question: {user_query}

Answer:"""

    inputs = tokenizer(input_text, return_tensors="pt", truncation=True, max_length=1024)
    outputs = model.generate(**inputs, max_new_tokens=100, num_beams=4)
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

# Run this in a NEW cell after the SUCCESS message
query = "What is the primary role of the Rambha-LP payload on Chandrayaan-3?"
result = rag_chain.invoke(query)
print(result)

# You can change the text inside the quotes to anything you want!
new_question = "What are the scientific objectives of the Aditya-L1 mission?"

print(ask_isro_ai(new_question))

# You can change the text inside the quotes to anything you want!
new_question = "Based on the RAMBHA-LP data, how does the lunar electron density change between the lunar day and the beginning of the lunar night?"

print(ask_isro_ai(new_question))

# 1. Increase search depth to find the deployment manual
retriever = vector_store.as_retriever(search_kwargs={"k": 5})

# 2. Ask the question (Notice the fixed quotes at the end)
new_question = "Which major rock-forming elements did the Alpha Particle X-ray Spectrometer (APXS) identify in the lunar soil near the south pole?"

# 3. Call your manual function
print(f"Searching 273 pages...\n")
print(ask_isro_ai(new_question))

new_question = "What are the two radioactive sources used in the APXS instrument to excite the lunar surface?"

print(ask_isro_ai(new_question))

# Save the FAISS index to your Google Drive
vector_store.save_local("/content/drive/MyDrive/ISRO_Chandrayan3/faiss_index")
print("✅ Vector store saved! Now your website can load it instantly.")

# 1. Create a folder in your Drive to store the data
!mkdir -p "/content/drive/MyDrive/Chandrayaan3_Project/unzipped_data"

# 2. Copy the files from the local Colab disk to your permanent Drive
print("🚀 Copying 273 pages to Google Drive... this may take a moment.")
!cp -r "/content/unzipped_isro_data/." "/content/drive/MyDrive/Chandrayaan3_Project/unzipped_data/"
print("✅ Done! Your data is now permanently saved in your Drive.")

!rm -rf /content/unzipped_isro_data

!rm -rf "/content/drive/MyDrive/Chandrayaan3_Project/unzipped_data"

